server:
  port: 8081
spring:
  application:
    name: cashtracker-invest
  datasource:
    url: jdbc:mysql://localhost:3306/invest?useSSL=false
    username: root
    password: Dip4rudp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/